### ISSUE TITLE
Render to multiple cameras

### ISSUE THREAD

**Issue by michidk** [kode80/kode80CloudsUnity3D#3]
Hey is it possible to render to multiple cameras?
In the kode80Clouds script, there is only one field for the target camera.. i have to render to multiple cameras. Is this somehow possible (without creating a second instance of the kode80clouds script)?

**Comment by kode80** [comment]
If it's not multiple cameras simultaneously, then you can just use the SetCamera() method on the kode80 Clouds component to switch cameras at runtime. 

If you do need to render multiple cameras simultaneously then you will need to use multiple kode80 Clouds instances as it works over several frames and needs to keep track of camera properties between frames (for temporal reprojection).

**Comment by michidk** [comment]
Sadly i have to display multiple cameras simultaneously.
Thanks!
