### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by Zimex** [kode80/kode80CloudsUnity3D#6]
Hello
While testing Your clouds package I found out that  switching platform to iOS makes it look way worse than normally. Do You  support that platform and have some workaround for this ? I'm sending screenshots of the same demo scene in new project with "iOS"  and "PC, Mac and Linux Standalone" platform set in unity 5.3.4.
![screen shot 2016-06-21 at 16 14 45 2](https://cloud.githubusercontent.com/assets/6368312/16303739/9e58edc0-3952-11e6-96b8-6e7f1365a0f2.png)
![screen shot 2016-06-21 at 16 16 23 2](https://cloud.githubusercontent.com/assets/6368312/16303741/a127f03c-3952-11e6-9679-bafcf2a8a521.png)

**Comment by kode80** [comment]
No, mobile platforms are not currently supported. At some point I would like investigate this however.
